use redactable::{Secret, SensitiveDisplay};

#[test]
fn debug_keeps_production_redaction_in_tests() {
    #[derive(SensitiveDisplay)]
    enum LoginError {
        #[error("login failed for {user} {password}")]
        Invalid {
            #[not_sensitive]
            user: String,
            #[sensitive(Secret)]
            password: String,
        },
    }

    let err = LoginError::Invalid {
        user: "alice".into(),
        password: "hunter2".into(),
    };
    let debug = format!("{err:?}");
    assert_eq!(debug, "login failed for alice [REDACTED]");
}

// SensitiveDual supplies structural traversal and template formatting together.
// Its single expansion coordinates both implementations.
mod dual_derive {
    use redactable::{
        Redactable, RedactableWithFormatter, Sensitive, SensitiveDisplay, SensitiveDual, Token,
    };

    /// {0}
    #[derive(Clone, SensitiveDual, serde::Serialize)]
    struct Email(#[sensitive(Token)] String);

    #[test]
    fn used_inside_sensitive_container() {
        #[derive(Clone, Sensitive, serde::Serialize)]
        struct UserProfile {
            #[not_sensitive]
            name: String,
            email: Email,
        }

        let profile = UserProfile {
            name: "alice".into(),
            email: Email("alice@example.com".into()),
        };

        let redacted = profile.redact();
        assert_eq!(redacted.name, "alice");
        // Token policy applied via RedactableWithMapper from Sensitive
        assert_eq!(redacted.email.0, "*************.com");
    }

    #[test]
    fn display_formatting_works() {
        let email = Email("alice@example.com".into());
        let display = format!("{}", RedactableWithFormatter::redacted_display(&email));
        // Token policy applied via RedactableWithFormatter from SensitiveDisplay
        assert_eq!(display, "*************.com");
    }

    #[test]
    fn structural_redaction_works_directly() {
        let email = Email("alice@example.com".into());
        let redacted = email.redact();
        assert_eq!(redacted.0, "*************.com");
    }

    #[test]
    fn debug_comes_from_sensitive_display() {
        // Debug is generated by SensitiveDisplay (Sensitive skips it in dual mode).
        // Test builds preserve the production redacted template.
        let email = Email("alice@example.com".into());
        let debug = format!("{email:?}");
        assert_eq!(debug, "*************.com");
    }

    #[test]
    fn used_inside_sensitive_display_container() {
        // Email implements RedactableWithFormatter (from SensitiveDisplay),
        // so it can be used as a field inside a SensitiveDisplay template.
        #[derive(SensitiveDisplay)]
        #[error("notification to {email}")]
        struct Notification {
            email: Email,
        }

        let notification = Notification {
            email: Email("alice@example.com".into()),
        };
        let display = format!(
            "{}",
            RedactableWithFormatter::redacted_display(&notification)
        );
        assert_eq!(display, "notification to *************.com");
    }
}
