use super::*;

#[test]
fn debug_is_unredacted_in_tests() {
    #[derive(SensitiveDisplay)]
    enum LoginError {
        #[error("login failed for {user} {password}")]
        Invalid {
            user: String,
            #[sensitive(Secret)]
            password: String,
        },
    }

    let err = LoginError::Invalid {
        user: "alice".into(),
        password: "hunter2".into(),
    };
    let debug = format!("{err:?}");
    assert!(debug.contains("hunter2"));
}

// Test that a type can derive both Sensitive and SensitiveDisplay when it needs
// structural traversal (for use inside Sensitive containers) AND display formatting.
// `SensitiveDual` authenticates and generates both halves in one expansion.
mod dual_derive {
    use redactable::{
        Redactable, RedactableWithFormatter, Sensitive, SensitiveDisplay, SensitiveDual, Token,
    };

    /// {0}
    #[derive(Clone, SensitiveDual)]
    #[cfg_attr(feature = "slog", derive(serde::Serialize))]
    struct Email(#[sensitive(Token)] String);

    #[test]
    fn used_inside_sensitive_container() {
        #[derive(Clone, Sensitive)]
        #[cfg_attr(feature = "slog", derive(serde::Serialize))]
        struct UserProfile {
            name: String,
            email: Email,
        }

        let profile = UserProfile {
            name: "alice".into(),
            email: Email("alice@example.com".into()),
        };

        let redacted = profile.redact();
        assert_eq!(redacted.name, "alice");
        // Token policy applied via RedactableWithMapper from Sensitive
        assert_eq!(redacted.email.0, "*************.com");
    }

    #[test]
    fn display_formatting_works() {
        let email = Email("alice@example.com".into());
        let display = format!("{}", RedactableWithFormatter::redacted_display(&email));
        // Token policy applied via RedactableWithFormatter from SensitiveDisplay
        assert_eq!(display, "*************.com");
    }

    #[test]
    fn structural_redaction_works_directly() {
        let email = Email("alice@example.com".into());
        let redacted = email.redact();
        assert_eq!(redacted.0, "*************.com");
    }

    #[test]
    fn debug_comes_from_sensitive_display() {
        // Debug is generated by SensitiveDisplay (Sensitive skips it in dual mode).
        // In test builds, the unredacted Debug impl shows actual values.
        let email = Email("alice@example.com".into());
        let debug = format!("{email:?}");
        assert!(
            debug.contains("alice@example.com"),
            "test-mode Debug should show actual value, got: {debug}"
        );
    }

    #[test]
    fn used_inside_sensitive_display_container() {
        // Email implements RedactableWithFormatter (from SensitiveDisplay),
        // so it can be used as a field inside a SensitiveDisplay template.
        #[derive(SensitiveDisplay)]
        #[error("notification to {email}")]
        struct Notification {
            email: Email,
        }

        let notification = Notification {
            email: Email("alice@example.com".into()),
        };
        let display = format!(
            "{}",
            RedactableWithFormatter::redacted_display(&notification)
        );
        assert_eq!(display, "notification to *************.com");
    }
}
