//! Adapters for emitting redacted values through `slog`.
//!
//! This module connects redacting derives and the Bypass family with `slog`.
//! A value carrying JSON is emitted through nested-value support; a text-only
//! value is emitted as a string.
//!
//! It is responsible for:
//! - Applying the operation selected by each adapter or named declaration.
//! - Avoiding fallible logging APIs: serialization failures are represented as
//!   placeholder strings rather than propagated as errors.
//!
//! It does not configure `slog`, define redaction policy, or attempt to validate
//! that a `Redactable` implementation performs correct redaction.

use std::fmt::{Debug, Display};

#[cfg(feature = "tracing")]
use crate::tracing::TracingRedacted;

use serde::Serialize;
use slog::{Key, Record, Result as SlogResult, Serde, Serializer, Value as SlogValue};

use crate::{
    policy::RedactionPolicy,
    redaction::{
        BypassDebugRedaction, BypassDisplayRedaction, BypassJsonRedaction, BypassRedactionMarker,
        RedactedValue, SensitiveValue, SensitiveWithPolicy, ToRedacted, serialize_redacted_json,
    },
};

/// Marker trait for types whose `slog` integration always emits logging-safe output.
///
/// This trait requires `slog::Value` so the type can be logged with slog.
/// Implementors are safe because their `slog::Value` implementation either
/// redacts its value or emits a value explicitly declared non-sensitive.
///
/// This trait is implemented only for logging-safe adapters and wrappers. It is
/// not a blanket impl for raw types.
///
/// ```compile_fail
/// use redactable::slog::SlogRedacted;
///
/// fn assert_slog_redacted<T: SlogRedacted>() {}
///
/// assert_slog_redacted::<String>();
/// ```
pub trait SlogRedacted: SlogValue {}

impl<T: SlogRedacted + ?Sized> SlogRedacted for &T {}

fn emit_value(
    value: &RedactedValue,
    record: &Record<'_>,
    key: Key,
    serializer: &mut dyn Serializer,
) -> SlogResult {
    match value.structured() {
        Some(json) => {
            let nested = Serde(json.clone());
            SlogValue::serialize(&nested, record, key, serializer)
        }
        None => serializer.emit_str(key, &value.text()),
    }
}

// =============================================================================
// impl_slog_redacted! — SlogValue + SlogRedacted for ToRedacted types
// =============================================================================
//
// Most types in this module share the same SlogValue body: delegate to
// `emit_value(&self.to_redacted(), ...)`. This macro generates both
// the SlogValue and SlogRedacted impls for those types.

macro_rules! impl_slog_redacted {
    // With generics: `@ [T, P] Type<T, P> where Bounds`
    (@ [$($gen:ident),+] $ty:ty where $($bounds:tt)+) => {
        impl<$($gen),+> SlogValue for $ty where $($bounds)+ {
            fn serialize(
                &self,
                record: &Record<'_>,
                key: Key,
                serializer: &mut dyn Serializer,
            ) -> SlogResult {
                emit_value(&self.to_redacted(), record, key, serializer)
            }
        }

        impl<$($gen),+> SlogRedacted for $ty where $($bounds)+ {}
    };
    // Without generics: `Type`
    ($ty:ty) => {
        impl SlogValue for $ty {
            fn serialize(
                &self,
                record: &Record<'_>,
                key: Key,
                serializer: &mut dyn Serializer,
            ) -> SlogResult {
                emit_value(&self.to_redacted(), record, key, serializer)
            }
        }

        impl SlogRedacted for $ty {}
    };
}

impl_slog_redacted!(RedactedValue);
impl_slog_redacted!(@ [T, P] SensitiveValue<T, P> where T: SensitiveWithPolicy<P>, P: RedactionPolicy);
impl_slog_redacted!(@ [T] BypassDisplayRedaction<T> where T: Display);
impl_slog_redacted!(@ [T] BypassDebugRedaction<T> where T: Debug);
impl_slog_redacted!(@ [T] BypassJsonRedaction<'_, T> where T: Serialize + ?Sized);

/// Extension trait for logging redacted values through slog.
///
/// Both methods borrow `self`. `slog_redacted` returns a borrowed adapter that
/// runs the producer each time slog serializes the record and emits the value's
/// redacted text; `slog_redacted_json` runs the producer at the call and returns
/// an owned value that serializes as redacted JSON.
///
/// Requires [`ToRedacted`], which only types with a declared sink value
/// implement - raw passthrough leaves like `String` cannot be certified as
/// redacted slog output. Every derived type qualifies, as do
/// [`crate::BypassDisplayRedaction`], [`crate::BypassDebugRedaction`],
/// [`crate::BypassJsonRedaction`] and [`crate::BypassTextRedaction`].
/// [`crate::BypassRedaction`] deliberately does not: wrap the value in
/// [`crate::BypassJsonRedaction`] to log it as JSON. [`BypassRedactionMarker`]
/// does not either; it forwards its inner value as a plain slog value.
///
/// # Panics
///
/// For structural values generated by `Sensitive` and `SensitiveDual`,
/// producing the value clones `self` before redacting it, so these methods
/// inherit every panic from `Clone`: a traversed [`std::cell::RefCell`] with a
/// live mutable borrow panics at the log call. `SensitiveDisplay` producers
/// format the borrowed value through the crate's formatter, which renders such
/// a cell as `<borrowed>`; `NotSensitiveDisplay` inherits the type's own
/// `Display`.
///
/// ## Example
/// ```
/// # #![allow(hidden_glob_reexports)]
/// # pub use redactable::*;
/// use redactable::slog::SlogRedactedExt;
/// use redactable::{Secret, Sensitive};
///
/// #[derive(Clone, serde::Serialize, Sensitive)]
/// struct Event { #[sensitive(Secret)] token: String }
/// # fn main() {
/// use ::slog::{Discard, Logger};
/// let event = Event { token: "secret".into() };
/// let logger = Logger::root(Discard, ::slog::o!());
/// ::slog::info!(logger, "event"; "data" => event.slog_redacted_json());
/// # }
/// ```
pub trait SlogRedactedExt: ToRedacted {
    /// Wraps `&self` for slog logging of its redacted text.
    ///
    /// A JSON-carrying value is emitted as compact JSON text, as with
    /// tracing's display adapter.
    ///
    /// This borrowed adapter requires a sized producer. The owned JSON adapter
    /// also accepts unsized producers.
    ///
    /// ```compile_fail
    /// use redactable::{BypassTextRedaction, ToRedacted};
    /// use redactable::slog::SlogRedactedExt;
    ///
    /// let value = BypassTextRedaction("safe output".to_owned());
    /// let producer: &dyn ToRedacted = &value;
    /// let _ = producer.slog_redacted();
    /// ```
    fn slog_redacted(&self) -> RedactedDisplayValue<'_, Self>
    where
        Self: Sized,
    {
        RedactedDisplayValue::new(self)
    }

    /// Returns a `slog::Value` that serializes as this value's redacted JSON.
    ///
    /// A text-only producer is read as `{"message": text}`. If serializing a
    /// redacted value into `serde_json::Value` fails, the JSON is the fixed
    /// string `"[REDACTED]"`.
    #[must_use]
    fn slog_redacted_json(&self) -> RedactedValue {
        RedactedValue::from_json(self.to_redacted().json())
    }
}

impl<T: ToRedacted + ?Sized> SlogRedactedExt for T {}

// Special cases: these don't use emit_value(&self.to_redacted(), ...)

impl<T> SlogValue for BypassRedactionMarker<T>
where
    T: SlogValue,
{
    fn serialize(
        &self,
        record: &Record<'_>,
        key: Key,
        serializer: &mut dyn Serializer,
    ) -> SlogResult {
        self.0.serialize(record, key, serializer)
    }
}

impl<T> SlogRedacted for BypassRedactionMarker<T> where T: SlogValue {}

/// Helper for `NotSensitive` derive-generated slog impls.
///
/// Serializes the value directly as structured JSON without redaction.
/// Not intended for direct use - called by generated code.
#[doc(hidden)]
pub fn __slog_serialize_not_sensitive<T: Serialize>(
    value: &T,
    record: &Record<'_>,
    key: Key,
    serializer: &mut dyn Serializer,
) -> SlogResult {
    let json_value = serialize_redacted_json(value);
    let nested = Serde(json_value);
    SlogValue::serialize(&nested, record, key, serializer)
}

/// Wrapper that emits a producer's redacted text through slog.
///
/// Use [`SlogRedactedExt::slog_redacted`] for ergonomic construction, or call
/// `RedactedDisplayValue::new(&value)` directly.
pub struct RedactedDisplayValue<'a, T: ?Sized>(&'a T);

impl<'a, T: ?Sized> RedactedDisplayValue<'a, T> {
    /// Wraps a reference to a `ToRedacted` value for slog logging.
    pub fn new(value: &'a T) -> Self {
        Self(value)
    }
}

// The producer is the admission bound. It selects the content; a JSON
// representation is emitted as compact text.
impl<T> SlogValue for RedactedDisplayValue<'_, T>
where
    T: ToRedacted,
{
    fn serialize(
        &self,
        _record: &Record<'_>,
        key: Key,
        serializer: &mut dyn Serializer,
    ) -> SlogResult {
        let text = self.0.to_redacted().text();
        serializer.emit_str(key, &text)
    }
}

impl<T> SlogRedacted for RedactedDisplayValue<'_, T> where T: ToRedacted {}

#[cfg(feature = "tracing")]
impl<T> TracingRedacted for RedactedDisplayValue<'_, T> where T: ToRedacted {}
