//! A raw passthrough value must not satisfy `SlogRedactedExt`.
//!
//! `RedactableWithFormatter` is implemented as passthrough for `String` and
//! scalars so they can format inside redacted templates. The extension trait
//! therefore also requires `ToRedacted` (generated by the display
//! derives); without that gate, `slog_redacted()` compiled on a raw
//! `String`, emitted the raw value to slog, and carried the `SlogRedacted`
//! certification marker.

use redactable::slog::SlogRedactedExt;

fn require_certified<T: SlogRedactedExt>(_: &T) {}

fn main() {
    let password = String::from("hunter2");
    require_certified(&password);
}
